### ISSUE TITLE
Segmentation issue - problem with demosaicing?

### ISSUE THREAD

**Issue by wooksh** [MSKCC-Computational-Pathology/DMMN-ovary#1]
Hello,

Recently, I've read Your publication and I tought it might be useful for my own medical research. I collaborate with gynecologists and I would like to explore an idea of using results produced with Your neural network in an analysis of patients' survival. At the moment, I am trying to test your network to determine potential samples collection prerequisites and future research expenses, but I faced a problem. I will describe it below.

Firstly, I have downloaded a trained ovary model. I haven't noticed any example data on the project's github page to either run already taught neural network or to train it. Therefore, to perform test segmentation I have downloaded and used as inputs images of an ovarian cancer from the Cancer Imaging Archive.
Direct link to the dataset is following:
https://faspex.cancerimagingarchive.net/aspera/faspex/external_deliveries/56?passcode=939306e2a7bc58fbc19e5085deb4128b6b268d20

For the test I used only one .SVS image from whole dataset. After running scripts "slidereader_coords.py" and "inference.py", an output bitmap has been generated. I couldn't open it as BMP image ("BMP image has bogus header data"), so I saved it with pillow python module to .PNG. I send You the obtained image in an attachment. In my opinion it looks like some problem with image's bayerization (mosaicing). Perhaps, the device you used to capture tissue image uses different method of image bayerisation/mosaicing than the device that captured images I used.

Because of that I would like to ask whether you could provide me more details concerning a neccessary format of the input images and model of the device that You used to capture tissue images or perhaps you could provide any example data that is known to work with the program.

I will appreciate any help.

Kind regards,
Łukasz Ciecierski

![predictions](https://user-images.githubusercontent.com/11035320/185955308-c2a7bd9c-5d45-468a-8a43-c7e98e949133.png)

**Comment by davidjoonho1987** [comment]
Dear Lukasz,

Thank you for your interest. To use my model, I recommend you to use .svs image scanned in 20x. To open BMP images, I use IrfanView.

Unfortunately, we do not plan to provide example data.

I hope this answers your question.

David

**Comment by wooksh** [comment]
That was it. This time I used 20x dataset for ovarian cancer:
https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=83593077

And I managed to open the bitmap with IrfanView. Everything works as expected.
Thank You very much for help!

Łukasz
