### ISSUE TITLE
seek help

### ISSUE THREAD

**Issue by Sakura-a-a** [MSKCC-Computational-Pathology/DMMN-ovary#2]
Dear author, I take the liberty to disturb you. I am a college student. I want to get your data set of ovarian cancer research for my graduation project.I guarantee that the data obtained will not be used for business. If you see this message and have time, please send it to me by email, and I will contact you later.

**Comment by davidjoonho1987** [comment]
Thanks for your interest! Unfortunately, we do not plan to release the ovarian data set.
